### ISSUE TITLE
Tutorial Link Broken

### ISSUE THREAD

**Issue by bsbechtel** [ryanswapp/meteor-pdf-tutorial#2]
Looks like the link to your tutorial page is broken (or you took it down). I had this saved for a while, and was interested in following it to generate pdfs in my own app. I'd be very interested in accessing the content if you've moved it elsewhere. Thanks.

**Comment by ryanswapp** [comment]
Hi! Ya I shut down my wordpress site and moved everything to Medium. Although, I think you managed to find it, right? It looked like I had a recommendation from you :)

Here is the link if not https://medium.com/@ryanswapp/getting-started-with-meteor-and-react-d411a87a1674

I also just updated the README. Thanks for pointing that out! :+1:

**Comment by bsbechtel** [comment]
Yeah I did find it. Thanks for updating the links though!
